### ISSUE TITLE
Missing Definitions

### ISSUE THREAD

**Issue by shakna-israel** [pulkomandy/c.vim#1]
It looks like [this commit](https://github.com/pulkomandy/c.vim/commit/4159fe507815f897f088253645fa3501876519b0), broke [some things](https://news.ycombinator.com/item?id=28205136).

> ... complains about not having definitions for cppType and cppStatement.

**Comment by pulkomandy** [comment]
Can you specify which version of vim (or neovim?)

I have tested only with 8.2 so far, but the C and C++ base files are probably different in other versions.

**Comment by danielbarry** [comment]
I get the following error:

```vim
"main.cc" 134L, 3474B
Error detected while processing BufRead Autocommands for "*.cc"..FileType Autocommands for "*"..Syntax Autocommands for "*"..
function <SNR>4_SynSet[25]..script /home/user/.vim/syntax/cpp.vim:
line    2:
E28: No such highlight group name: cppType
line    6:
E28: No such highlight group name: cppStatement
Press ENTER or type command to continue
```

I can replicate this in version:

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 15 2021 12:29:39)
Included patches: 1-2434
```

**Comment by pulkomandy** [comment]
> script /home/user/.vim/syntax/cpp.vim

The script needs to be installed in .vim/after/syntax/{c,cpp}.vim so that it will complement the original files from vim. I think you have it installed in .vim/syntax, in which case it will completely override the original files.

**Comment by danielbarry** [comment]
@pulkomandy I just tested this now and it now loads correctly (see line 24 in image):

![Screenshot from 2021-08-18 01-44-59](https://user-images.githubusercontent.com/9805017/129737468-43e703e9-7af1-4528-a068-613f0770e8e8.png)

On line 34 of image, it seems to syntax highlight weirdly? The `int` is no longer highlighted and the semicolon appears as an 'error'?

A minimal example:

```cpp
#include <cstdio>

int main(int argc, char** argv){
  int i = 0;
  if(true)
    std::printf("Test %i\n", (int)i++);
  for(int x = 0; x < 1; x++)
    std::printf("Test %i\n", (int)i++);
  for(
    int x = 0;
    x < 1;
    x++
  )
    std::printf("Test %i\n", (int)i++);
}
```

As rendered:

![Screenshot from 2021-08-18 01-56-04](https://user-images.githubusercontent.com/9805017/129739382-b0fcf6c4-7f6b-4963-be44-97925d07a91a.png)

As you can see, this causes different behaviour of the `int` declaration of the for-loop depending on whether it is broken up onto multiple lines or not.

**Comment by pulkomandy** [comment]
Thanks for the example, I had some problems with for loops but it was in a big file and I did not manage to reproduce reliably. I will see if I can understand what's happening with this simplified example.

I am also trying to understand why there is an error highlight on the ; (this comes from the default c.vim shipped with vim, but I do not understand which part of it yet and why the changes here make it think there is a syntax error there).

**Comment by danielbarry** [comment]
@pulkomandy Can confirm it now appears to operate fine. Thanks for checking this out so quickly!
